@startuml
title Pressure BC
skinparam defaultFontSize 20
start
:loop vertex;
:find cooresponding node:ipoint;
if (ipoint is on dmomain: prevent halo node) then (yes)
  :get v_domain;
  :get specified pressure P_ext;
  :get density,velocoty in domain:Density,Velocity;
  :get pressure in domain:Pressure;
  :calculate speed of sound accoring to domain value and isoentropic relation;
  :calculate mach number according to domain value;
  :calculate entropy and Riemann valable according to domain value;
  :correct Density,Velocity accoring to Riemann value,P_ext; and calculate v_outlet;
  :set conv_scheme,using V_domain as left state, v_outlet as right state;
  :calculate flux;
   

@enduml